# Generated by Django 2.1.2 on 2018-10-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_photo', models.ImageField(upload_to='')),
                ('s_address', models.CharField(max_length=50)),
                ('s_phone', models.CharField(max_length=50)),
                ('s_blood', models.CharField(max_length=50)),
                ('std', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.StudenInfo')),
            ],
        ),
    ]
