# Generated by Django 2.1.2 on 2018-10-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studeninfo',
            name='std_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentClass'),
        ),
    ]
