# Generated by Django 2.1.2 on 2018-10-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20181020_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
